### PR TITLE
Chat look and feel part 2

### PR DESCRIPTION
**Pull request by LordSk**
This includes
- A flashier highlight, as requested by @oy 
- A black background when showing chat to facilitate reading
- A box behind the category when typing
- A few fixes regarding whispers/highlights

Here is a video preview:
https://www.youtube.com/watch?v=-4BYnNLqTNE

### CODE REVIEW

**Comment by LordSk** [comment]
@Dune-jr 
image

**Comment by 1stDecadeTW** [comment]
I like it, maybe the black chat box could be enable/disable in config menu and colors of the chat could be configurables also.

**Comment by ChillerDragon** [comment]
Imo this is a big downgrade. The chat background looks annoying and the **colors don't fitt at all**.
And still strongly agianst ids and [Team] in front of the names.

The only think that is an upgrade is how the text looks with the shadow <3
But how the whole chat currently looks is not acceptable for me ._.

( This is a personal opinion obviously )

**Comment by Learath2** [comment]
- IDs belong in debug mode or at least in an off by default setting.
- [Team]/[Whisper] is redundant information already conveyed by the colour of the line.
- Fading blue box highlight is irritating to the eye.

For whisper maybe adopt the [convention](https://github.com/ddnet/ddnet/blob/master/src/game/client/components/chat.cpp#L573-L588) we've been using with → and ←.

The current highlight isn't all that bad but if you want to improve it I think you should look at playing around with the colour, or maybe bolding the nickname.

**Comment by Dune-jr** [comment]
> * Fading blue box highlight is irritating to the eye.

Well that shouldn't happen too much, it's only for pings, which should be rare.

> * [Team]/[Whisper] is redundant information already conveyed by the colour of the line.

I agree, the chat became good enough that they're no longer necessary imo. But I can see why one would want them.

> * IDs belong in debug mode or at least in an off by default setting.

I very much agree, the default chat shouldn't show IDs - but revamping IDs/turning them off by default is for a different PR afaik. 

I think the demo video will look better when they'll be changed/turned off :)

> For whisper maybe adopt the [convention](https://github.com/ddnet/ddnet/blob/master/src/game/client/components/chat.cpp#L573-L588) we've been using with → and ←.

To me, that sounds good. I think we need a way to tell apart outgoing from incoming messages, indeed.

**Comment by LordSk** [comment]
As I stated before, [Team]/[Whisper] can be removed once we have a proper whisper system.
IDs is a separate issue, see here #1591.

@ChillerDragon
> The chat background looks annoying and the **colors don't fitt at all**.

I don't get that response. The background is there to help you read when you actually **want to read the chat**. Now of course if I could, I'd make something fancier, but we are working in a limited space.
Which colors don't fit? Fit with what? Please elaborate, or better yet, propose a better solution.

I should've probably specified it originally, but the video showcases an **extreme** example of chat.
There are a lot of messages (more than 1 a second), lots of whispers / highlights and the map itself is very bright, making harder to read chat. This does not represent the **average** use players will have of it.

**Comment by ChillerDragon** [comment]
> but the video showcases an extreme example of chat.
> There are a lot of messages (more than 1 a second), lots of whispers / highlights and the map itself is very bright, making it harder to read chat.

@LordSk this sounds like you assume this never happens same with @Dune-jr assuming pings are rare.

If you are on busy servers and/or currently in an important position ( gameplay wise or admin/staff member ). This is exactly how an normal chat looks like.

> Please elaborate, or better yet, propose a better solution.

I am sorry i am not a designer or something like that. And i respect your work. As i already said I like the shadows. But the rest is worse than the old chat so my "suggestion/solution" is staying with the old chat. Red for highlighting no background. No ids and no [Team] in front of the messages. Everything works fine in 0.6

And anways in my opinion we shouldn't change the design to something that makes the expirience of teeworlds power users worse just because its okay for the average user.

> I don't get that response.

I am sorry it is hard for me to explain. It just makes me feel very displeasing looking at it.
I can just say that it should stay simple. As simple as possible.
> I'd make something fancier, but we are working in a limited space

So you don't space or something fancy.

**Comment by 1stDecadeTW** [comment]
@LordSk @ChillerDragon  here is my design propose. 

I like your "flashier highlight", maybe it could be implemented in personal messages and it should be custimizable in settings because actual one is too showy (but is nice :D).

screenshot_1

**Comment by Dune-jr** [comment]
I think with the current outline, the blue background boxes isn't very useful at all in the "Show chat" mode.

Actually, I don't think we need those blue backgrounds at all. They look neat, but the outline is already catchy enough. But maybe I'm being a bit conservative :)

**Comment by 1stDecadeTW** [comment]
@Dune-jr @ChillerDragon  those chat bubbles are who they will look like when you open the chat and start typing: 
"T" key = All chat bubble.
"Y" key = Team chat bubble.
"P" key personal/private message chat bubble.
When spectating, the spectator purple bubble chat will appear.

Look at @LordSk example video: https://youtu.be/-4BYnNLqTNE?t=13

screenshot_1

**Comment by LordSk** [comment]
@oy so what should I do then? Remove it, tune it down, keep it like this?
______________________________________________
This is where I'm at right now, gently fade the black box and reduce its height. I'll add the possibility to scroll the text eventually.

image

Also @1stDecadeTW , in #1590 we had a discussion regarding colors.

**Comment by oy** [comment]
@LordSk maybe tune it down and see how it looks?

**Comment by Fisico** [comment]
> @oy so what should I do then? Remove it, tune it down, keep it like this?
> 
> This is where I'm at right now, gently fade the black box and reduce its height. I'll add the possibility to scroll the text eventually.
> 
> image
> 
> Also @1stDecadeTW , in #1590 we had a discussion regarding colors.

@LordSk 
maybe make the "Spectators:" Text smaller than the actual text you are typing.

**Comment by ChillerDragon** [comment]
@LordSk really like the fade. I think it could look on top and bottom very good aswell. A very short but still smooth enough fade would be nice to make the background less dominant and distracting. A good design is invisible c:

**Comment by Dune-jr** [comment]
Good job, @LordSk!

I like it that the background was removed during the show-chat, I think the neon outline highlights it enough already

**Comment by oy** [comment]
Looks good to me 👍

**Comment by ChillerDragon** [comment]
Looks better imo. But for me the new highlight background and colors still hurt my eyes ._.

**Comment by ChillerDragon** [comment]
@oy what is the problem with the old highlight? It was perfect. It looked simple and good. And was always easy to spot.

**Comment by LordSk** [comment]
image

This is what a smaller category text would look like, suggested by @Fisico, thoughts?
(I did not include it yet)

**Comment by Dune-jr** [comment]
My thoughts: I have a slight preference for the bigger category, but I don't mind.

**Comment by fokkonaut** [comment]
What about personal color changer in the settings? Im for example colorblinded and the red text was really nice for me. The new one i literally cant say what color it is and for me its not much different from the normal white text.

**Comment by Dune-jr** [comment]
Could a cl_blindmode that sets highlights to plain red fix it?

**Comment by oy** [comment]
Adding a colour tab sounds bad.

**Comment by Learath2** [comment]
Maybe a HUD tab where these things are customizable? I'm not sure though. I
don't really think everything should be customizable. I'm leaning more
towards a `cl_blindmode` option.

Or maybe we could tie the colours to settings that we just don't show in
the client?

**Comment by Dune-jr** [comment]
Anyway, this isn't specific to this PR. The current chat is already that way. It should be a separate issue and not block progress or merge of this PR imo.

To the issue: just have a `cl_blindmode` console option revert to the old red highlight for those that really need it. The rest can wait for an advanced/HUD tab, *if* we end up having one.

**Comment by LordSk** [comment]
Alright looks like I'm done here then, @oy if you want to validate the merge.

**Pull request merged**
