### PR TITLE
Split base system.c/h into different components

### PR DESCRIPTION
**Pull request by Robyt3**
Splits the base system into more manageable components. Including `system.h` includes all components, so no code outside base needs changes.
- system - header includes other component headers, contains some functions that didn't fit anywhere
   - debug - all dbg_* functions
   - fileio - all io_* functions
   - filesystem - all fs_* functions
   - memory - all mem_* functions
   - network - all net_* functions and static functions only used with networking code
   - strings - all str_* functions
   - threading - all thread_* lock_* and semaphor_* functions
   - time - all time_* functions, str_timestramp* functions so that strings doesn't depend on time

Imports for windows are correct and minimal. Will probably not be on the first try for the other platforms without testing thou.

### CODE REVIEW

**Comment by Dune-jr** [comment]
The Teeworlds baselib comes from https://github.com/matricks/baselib, by the way.
@matricks is/was no stranger to modular and well-structured programming, so I suppose it was written with a certain philosophy in mind, and one should carefully weigh the benefits and inconvenients of having everything in one module.

**Comment by Robyt3** [comment]
Having everything in system.c becomes very hard to maintain as more methods get added. Some separation is necessary, but the current state of the code looks good to me as a platform independence layer.

Do you know where I get the strcasecmp and strncasecmp includes from? Why does it work on one windows build but not on the other?

**Comment by Robyt3** [comment]
Finally. Now that was weird. It worked for me before but I had to add the check for !GNUC because _stricmp and _strnicmp are not available there.

**Comment by LordSk** [comment]
Who is this for?
Teeworlds is not a new project, these files have been this way for years and have barely changed, so why do this now? Have these files reached a critical/unmanageable mass? I don't think so.
What do we gain by doing this?
We certainly do not gain significant compilation speed, we might even lose some (I have not measured it, but [I'll leave this here](https://buffered.io/posts/the-magic-of-unity-builds/)).

I believe that we won't change these files much (if at all) until we release the final version of Teeworlds.
You've done an excellent job so far, but these kind of changes are not needed.

**Comment by Robyt3** [comment]
It's much easier to find what you are actually looking for without a global text search. Maybe they are managable for you because you are used to the code, but I think the overall readability needs to be improved to allow more **new developers** to understand and contribute something to the heap of remaining issues. Compilation time is only relevant when something changes, true, so this would rarely matter as the base is rarely changes. Even so if you decide to add new functions it's easier to find where they should go.

**Comment by heinrich5991** [comment]
> It's much easier to find what you are actually looking for without a global text search. Maybe they are managable for you because you are used to the code, but I think the overall readability needs to be improved to allow more **new developers** to understand and contribute something to the heap of remaining issues.

I think it's the opposite: It's much easier if everything is in one file: You're one text search away from the function (as opposed to some multi-file search that not every editor/setup supports).

**Pull request closed without merging**
