### PR TITLE
Experimental extended browser view

### LINKED ISSUE #2276: RFC: extend server browser view
I did some UI margin tweaks in the server browser (and the rest of the offline UI).
They were well received and I was asked to open discussion for a possible push to the vanilla client.
Ignore the favorites tab.

screenshot_2019-10-27_12-05-11
screenshot_2019-10-27_12-05-07

This is https://github.com/Dune-jr/teeworlds/commit/f5bf0bcb6d5ddde46e7169bc1585b7b06f6ab5af

### PR DESCRIPTION
**Pull request by Dune-jr**
Closes #2276 

Code is not final, bad variable name, and the button to switch between modes should probably go away (?)
Thoughts?

> the zoom in makes the name column tight on 4:3 resolutions, although I believe the expanded view (the arrow on the right) was engineered for this use case
not sure if adaptive zoom in would be better

# 16:9
screenshot_2019-12-14_13-02-19
screenshot_2019-12-14_13-02-23
# 4:3
### With sidebar
screenshot_2019-12-14_13-01-55
screenshot_2019-12-14_13-01-57
### Collapsed sidebar
screenshot_2019-12-14_13-01-45
screenshot_2019-12-14_13-01-50

### CODE REVIEW

**Comment by oy** [comment]
That button looks odd. Maybe use a zoom icon(magnifying glass with +/-) for it and integrate it in the browser (maybe header top left?)?

**Comment by Dune-jr** [comment]
> the button to switch between modes should probably go away

I don't think the button should stay, it's a bit of an odd concept... we already have a button for collapsing/expanding the view.

If it's integrated in the browser it's not so bad, but I don't think that change is controversial enough to warrant making it optional.

**Comment by Dune-jr** [comment]
I just realized I forgot it affects the reset of the UI as well (settings)
If you think this should be an option I'll look into integrating that if you want.

screenshot_2019-12-16_23-37-12
screenshot_2019-12-16_23-40-24
screenshot_2019-12-16_23-40-26
screenshot_2019-12-16_23-40-32

Without it:
screenshot_2019-12-16_23-41-45

**Comment by Dune-jr** [comment]
I asked some more opinions around, and it's not unanimous that the extended server browser view is better. Guess we're in for an option!

**Comment by oy** [comment]
When it's not just the server browser there should be an option in settings->general->client. Probably split that part into 2 columns like the game part above.
And it should probably effect the whole menu.

**Comment by Dune-jr** [comment]
> When it's not just the server browser there should be an option in settings->general->client. Probably split that part into 2 columns like the game part above.

Added an icon on the top right instead. Not sure if I like it though (didn't find so many good icons at [unicode/block/geometric_shapes](https://www.fileformat.info/info/unicode/block/geometric_shapes/list.htm) and [U+26F6](https://www.compart.com/en/unicode/U+26F6) is unavailable). Avoids introducing a localized string...

**Pull request merged**
