### PR TITLE
Inconvenience for windows

### PR DESCRIPTION
**Pull request by ChillerDragon**
Reduce diff to downstream

(cherry picked from commit https://github.com/ddnet/ddnet/commit/93d14a1ecabcd2662915b1b2549a971b885b16e5)

### CODE REVIEW

**Comment by Learath2** [comment]
Seems vanilla doesn't share this issue since they don't have curl including `windows.h` in an annoying way. Not sure if this fits here

**Comment by ChillerDragon** [comment]
> Seems vanilla doesn't share this issue since they don't have curl including `windows.h` in an annoying way. Not sure if this fits here

Yea I know the issue is not shared but still would be nice if ddnet and teeworlds would have the same math functions

**Comment by oy** [comment]
Yeah, could be done, when the conflicts are gone 👍

**Comment by ChillerDragon** [comment]
Solved

**Pull request merged**
