### PR TITLE
Minor improvements on GitHub workflow

### PR DESCRIPTION
**Pull request by Panquesito7**

### CODE REVIEW

**Comment by heinrich5991** [comment]
What does this improve? Running from master sounds like it reduces reproducibility.

Running on ubuntu-16.04 helps us keep backwards-compatibility.

**Comment by Panquesito7** [comment]
> Running from `master`

The `master` version has more bugfixes and
improvements than `v2`. It works pretty good for me.

**Comment by jxsl13** [comment]
what bug fixes that are relevant for this repository?

**Comment by heinrich5991** [comment]
https://github.com/actions/checkout/tree/be6c44d969b1b004a9e0f7853e9cc9977ea0f7f0#usage suggests to use itself with `actions/checkout@v2`.

**Comment by Panquesito7** [comment]
AFAIK, `master` seems to be faster.

**Comment by Panquesito7** [comment]
`master` version seems to be faster.

PR workflow runtime (this PR): [3m 37s](https://github.com/teeworlds/teeworlds/actions/runs/242099994).
Latest workflow runtime: [5m 49s](https://github.com/teeworlds/teeworlds/actions/runs/241981856).

Various other workflows run in about 3m and 50s.
See this one for example: [3m 46s](https://github.com/teeworlds/teeworlds/actions/runs/240535423).

It looks like the difference is about 15/10 seconds.
It's not a huge difference, but faster workflows are better. 🙂

**Comment by oy** [comment]
Checked all recent [workflows](https://github.com/teeworlds/teeworlds/actions) and there're couple of entries that finished in less than 4 min. Dunno if using the master would be much faster. Think we should stick to the stable v2.

**Comment by axblk** [comment]
The difference in runtime is probably just fluctuation, because the machine running the workload was on higher load.
In general, the time needed for the checkout is negligible compared to the build time. I would rather stay on the stable branch instead of saving a few seconds here.
Apart from this, `v2` always points to the latest 2.x release. In terms of commits `master` is even behind `v2`, as they are using `main` for the default branch now.

**Pull request closed without merging**
