### PR TITLE
Fully implement automatic download script, replaces #1344

### PR DESCRIPTION
**Pull request by Henningstone**
A clean and updated commit tree to implement automatic downloading of the SDL2 and freetype includes and DLL's.
Initial commit by Zwelf _(see #1344 / 67f63d34bf0a0d0a635e899da18df4e16fc47b92)_, picked up and redone by me, optimized by heinrich5991.

This pull request includes the full commit tree/history and replaces the original commit #1344 by Zwelf cleanly.

### CODE REVIEW

**Comment by oy** [comment]
Shouldn't use official files and not be part of the build process.

**Comment by heinrich5991** [comment]
I guess you mean "*should* use official files"?

**Comment by oy** [comment]
Yeah.

**Comment by Henningstone** [comment]
I thought it *should* be part of the build process so that the user doesn't need to mind about dependencies? When you say it shouldn't, how would you solve it then in a way that the user doesn't have to do much?

**Comment by oy** [comment]
The libs should either be installed already or the developer has to take care of that.
There could be a script in /scripts that a user could run to grab these.

**Pull request merged**
