### PR TITLE
Show chat in menu (closed #2161)

### LINKED ISSUE #2161: Please revert chat hide in menu
Could we please get the chat back? Also in menu and in demo editor and everywhere else where it was and where it was usefull. Everytime I write bye in chat and go to menu to disconnect i hear the chat ping but I don't know if the message is "ok bye" or "please wait". Also there is plenty of space so why hide it? It was also annoying when someone explained the vote menu to me in chat and I had to tab back in all the time. Also scanning demos for chat messages became really annoying.

It simply is a downgrade.

Here is the change by @SushiTee from 2012 that removed chat in menu:
https://github.com/teeworlds/teeworlds/commit/c74637ae6ded59a2eb31518f9cc7739d4e3b8afd#diff-da8e51385055fcc863833513a3930b15R392

### PR DESCRIPTION
**Pull request by ChillerDragon**
reverts https://github.com/teeworlds/teeworlds/commit/c74637ae6ded59a2eb31518f9cc7739d4e3b8afd#diff-da8e51385055fcc863833513a3930b15R392

see discussion at: https://github.com/teeworlds/teeworlds/issues/2161

### CODE REVIEW

**Comment by Dune-jr** [comment]
There may be readability issies with the settings menus, chat must be tested against that.

**Comment by ChillerDragon** [comment]
@Dune-jr sure it is not recommended to open menu for better chat readability. But forcing players to exit menu because the chat is turned off can be very annoying. I wonder why you have so many concerns about leaving it like it was working for decades. Short messages are always readable. Long messages if they are the latest ones work fine as well. Even in the worst settings tab (flags). The only place where chat is not readable is the map editor.

Hiding chat in menus especially in demos forces some players who need this feature on a daily base to use a custom client. And since there is nothing out there yet this will make the update to 0.7 harder. I see it was implemented to clear the ui but I don't think it is worth giving this useful functionality up to clean the ui a bit.

screenshot_2019-06-24_19-27-43

**Comment by Dune-jr** [comment]
Because when it was "working for decades" we didn't have a transparent menu.

There are probably ways to fix this issue like it was fixed with the scoreboard, e.g. only showing a few lines of chat

**Comment by ChillerDragon** [comment]
@Dune-jr because we have a transparent menu it works even better and there is no need to chop parts of the chat since it can be seen through the menu. And in the unusual case of it not being visible enough the player can leave the menu.

**Comment by oy** [comment]
It's not about the chat not being readable, it's about the menu in front of it not being readable.
Could be handled like the scoreboard: hold show chat pressed and then open the menu to have it shown all the time.

**Comment by ChillerDragon** [comment]
@oy ah true that makes sense. But I can tell you as someone who uses a transparent scoreboard in 0.6 already that maps are a bigger problem than the chat. I tried to produce the worst scenarios with max chat coverage. The worst was probably the vote reason but it also was fine enough.

screenshot_2019-06-24_21-43-18
screenshot_2019-06-24_21-43-26
screenshot_2019-06-24_21-43-28
screenshot_2019-06-24_21-43-31
screenshot_2019-06-24_21-43-35
screenshot_2019-06-24_21-44-49
screenshot_2019-06-24_21-45-23

**Comment by Fudgyking** [comment]
Feels like the 3rd pull request with this change. I don't like when something is fixed by just adding a setting, but maybe this is what should be done to end this debate once and for all.

**Comment by Dune-jr** [comment]
The general problem is that the menus use transparency without any sort of blur effect, and it is very difficult to achieve a good result like that. No easy fix unfortunately. @ChillerDragon's screenshots are worst-case scenarios and maybe not so bad.

**Comment by ChillerDragon** [comment]
@Dune-jr the probably most used 0.6 clients have the option for transparent menus and it worked just fine. Also the motd is transparent in vanilla since forever. The chat was always a smaller problem for me.

Bigger problems were playernames or textures in the map.

**Comment by Dune-jr** [comment]
Yeah, I think @ChillerDragon is right and the benefits of this PR outweigh the negatives

**Comment by jxsl13** [comment]
Me gusta!

**Pull request merged**
