### PR TITLE
Chat commands

### LINKED ISSUE #1852: Whisper target selection is not intuitive and not consistent (Ctrl-Tab does not work for highlights)
People are struggling with the whispers, I'm not sure what could be done though.

It doesn't matter as much for highlights because you can type the beginning of the name of the player and get it on the first try or two.

Maybe there should be a way to type the beginning of a player's name, somehow.

### PR DESCRIPTION
**Pull request by Dune-jr**
### Motivation

This feature namely fixes https://github.com/teeworlds/teeworlds/issues/1852 by adding a way to select a target by entering their name — and using the existing Tab mechanics to autocomplete. 

> People are struggling with the whispers, I'm not sure what could be done though.
> 
> It doesn't matter as much for highlights because you can type the beginning of the name of the player and get it on the first try or two.
> 
> Maybe there should be a way to type the beginning of a player's name, somehow.

This has not undergone any review of code or ergonomics, so it will probably need some adjustments. I took my inspiration from the Blizzard/Battle.net games chat system.

### Usage
I attempted the behavior of the command menu as intuitive and close as what the player would expect. It is difficult to do that without a bias, though, so I'd gladly take feedback.

- Starting any chat line with a `/` opens a command menu. 
  - Only the commands that match what is being typed are displayed
  - This only works for `All` and `Team` chat
- Commands can be typed in full or navigated using up and down arrows.
- Using `Tab` does not autocomplete commands, but it autocompletes player names
- A command can be executed using `Enter`
  - If the command is invalid and has no match, nothing happens (no chat message is sent, either)
  - If the command is invalid, the first partial match is autocompleted, with a space. For example, `/a` becomes `/all `, and `/fr` becomes `/friend `.
  - If the command is valid, it is executed
    - If the command expects a parameter (player name) and received none, it is not valid
- The command menu can be left using `Escape`
  - No command helper will be displayed again until the chat is closed
  - Chat lines will be sent regardless of whether they start with a `/`.
    - This avoids players being restricted to type special strings in the chat

#### Parameter selection
- It is not possible to select oneself.
- It is not possible to select a player that shares a nickname with someone else

### Commands
```cpp
	static CChatCommand s_aapCommands[] = {
		{"/all", " - Switch to all chat", &Com_All},
		{"/friend", " <player name>", &Com_Befriend},
		{"/m", " <player name>", &Com_Mute},
		{"/mute", " <player name>", &Com_Mute},
		{"/r", " - Reply to a whisper", &Com_Reply},
		{"/team", " - Switch to team chat", &Com_Team},
		{"/w", " <player name>", &Com_Whisper},
		{"/whisper", " <player name>", &Com_Whisper},
	};
```
https://github.com/Dune-jr/teeworlds/blob/305e04e597c7c7c0b8174248a855a28dc1ac915b/src/game/client/components/chat.cpp#L26-L35

- `/all`, `/team` and `/r` just switch from a chat mode to another, with the exception that `/r` only works if the player has already received a whisper at some point.

- `/w` & `/whisper` let you pick a whisper target e.g. `/w Slay` + Tab -> `/w Slayer *gV*` + Enter -> enters whisper mode 

- `/friend` and `/mute` are shortcuts to the ingame menus functions to befriend and ignore players. I found that it is much quicker to ignore spammy players that way rather than to browse the ingame menus. They also print a confirmation message in the chat as a server message.

### Code
I had to tweak `system.c` with two function additions: https://github.com/Dune-jr/teeworlds/commit/3d787ceadaf9628cd6371865fb6f62b4e4e755ee

- `str_clean_whitespaces` also removes double spaces in the middle of a string, so I had to rewrite it in `str_clean_whitespaces_simple`
- `str_skip_to_whitespace` does not let me use `const char*`, so I wrote `str_skip_to_whitespace_const`

There may be better ways.

### Visuals
image
image

### Possible improvements
- Improve the visuals
- Maybe directly execute parameter-less commands such as `/all` when one types `/a`. Maybe even allow things like `/whi Dune`
- Maybe let people use player IDs in some intuitive way. `/w 1` ? `/w 1:` ?
- Maybe gray helper text in the chat line, that lets you know the command expects a `<player name>` parameter

### CODE REVIEW

**Comment by heinrich5991** [comment]
The visuals look really great, good job! :)

Adding tests for functionality in src/base/system.c is easy, just add a new test to src/test/str.cpp. :) `cmake --build <build directory> --target run_tests` to run them.

`/r` has the problem of not going to the player you intended if someone whispers you directly before you hit enter. Blizzard solves that by expanding `/r` to `/w <last whisper target>` directly when you press the space bar after `/r`.

**Comment by Dune-jr** [comment]
Thanks. I'll look into adding a few tests.

> `/r` has the problem of not going to the player you intended if someone whispers you directly before you hit enter. Blizzard solves that by expanding `/r` to `/w <last whisper target>` directly when you press the space bar after `/r`.

This problem does not really occur in Teeworlds because typing `/r` and enter only brings you to the whisper prompt, displaying the selected player (so you can realize your mistake).

The fact that you cannot whisper someone in one line — with something like `/w heinrich5991 hello` may be a shortcoming. The problem is that it is somewhat difficult to implement this because player names may include spaces. You would then need to have some sort of behavior similar to the shell when autocompleting (e.g. `cd My` + Tab gives `cd "My Documents"`).

**Review by LordSk — CHANGES_REQUESTED** [review]
`/r` seems bugged (I answered myself apparently?).
When typing a *switch* command with a message, such as `/team message`, it will switch you to the correct chat but erase the message. A more preferable behaviour would be sending the message in the correct chat right away.
Same thing for whispers, `/w Dune message` should send Dune a message but currently it does nothing as it detects `Dune message` as a nickname. Perhaps the input line could get smarter and have a block dedicated to the nickname like so: /w **[Dune]** message.

**Comment by fokkonaut** [comment]
maybe change /r to /c (conversation). And is it possible to add commands serverside which the client will also see in the commands list?

**Comment by Dune-jr** [comment]
/r stands for /reply, is more common, and /command does not describe the action as well (reply to the last whisper).

Having server side commands showing up would require a protocol upgrade, so not possible until a new major version afaik.

**Comment by Dune-jr** [comment]
> I mean we don't have any messages yet which aren't initiated by the server. They all are, so people might think the server did it. Could just make the *** white or some other colour, or use different characters(* C *, * S *, ...), dunno. Just a small hint might be good.

_@oy in https://github.com/teeworlds/teeworlds/pull/2043#issuecomment-465965034_

Fixed by ccddc03

image

> * Fix `/r` (picks the wrong target, right now)

Fixed by 2fd4abb

> * Preserve parameters as the message when switching with `/all`, `/team` and `/r`.

Fixed by b6f086d and 81f8a03

> * Change the text in the input area when moving with arrow keys

Won't do, this causes issues, it messes with the autocomplete suggestions as the input area text change.

---

Note that there could easily be a `/con` command that lets you type console commands from the chat, but I don't think it would be very useful.

It would also be easy to implement a `/votekick`, but it doesn't sound like a good idea.

**Comment by oy** [comment]
Looks good. Could you fix the conflicts? Then we can merge it.

**Pull request merged**
