### PR TITLE
No need to force desktopsize when windowed [macOS]

### PR DESCRIPTION
**Pull request by Learath2**
I thought I'd open a separate issue for this

### CODE REVIEW

**Comment by oy** [comment]
@Learath2 what happens when you start the client in window-mode and the width and height differ from desktop size and the you toggle fullscreen while running?

**Comment by Learath2** [comment]
Toggling fullscreen is broken for me either way

**Comment by Learath2** [comment]
https://hg.libsdl.org/SDL/rev/be892626e1aa fixes the fullscreen toggle, however with fullscreen desktop the resolution being different breaks rendering

**Comment by oy** [comment]
When there's a SDL release with the fixes we can remove the forcing of the desktop resolution.
About the resizing: does that work on windows?

**Comment by Learath2** [comment]
I don't have access to a windows machine, it'd be great if someone could test that commit.

**Pull request closed without merging**
