### PR TITLE
Some more search bars

### PR DESCRIPTION
**Pull request by Dune-jr**
Close https://github.com/teeworlds/teeworlds/issues/2024
7f40c0e might be a bit hackish, but seems necessary to avoid a bug where the scrollbar stays too low (`s_ScrollValue` is handled in caller functions and not in `RenderFileDialog`... )

screenshot_2019-09-15_01-16-41
screenshot_2019-09-15_01-28-41
screenshot_2019-09-15_01-28-55

### CODE REVIEW

**Comment by ChillerDragon** [comment]
@Dune-jr is the map searchbar highlighted by default? The DDNet client for example has this search bar for a while now and I always start typing but nothing happens because it is not typing in the search bar. Would speed up things a lot if no mouse is involved.

**Comment by Dune-jr** [comment]
@ChillerDragon no

**Comment by ChillerDragon** [comment]
> @ChillerDragon no

Could you add that? <3

**Comment by Dune-jr** [comment]
Might want to merge 67a2323 as well then

**Pull request merged**
