### PR TITLE
Fix audio file "sfx_msg-client.wv"

### PR DESCRIPTION
**Pull request by clavinet**
"sfx_msg-client.wv", the sound that plays when something is written to the chat, had an annoying click at the end.
I removed just the short click at the end and kept the file intact otherwise (lossless edit in Audacity). Tested it with Teeworlds 0.7.3.1 and it plays fine.

### CODE REVIEW

**Comment by Fudgyking** [comment]
Am I the only one who cant hear the difference?

**Comment by clavinet** [comment]
Here is a comparison:
https://share.riseup.net/#XRwy5UgplnSvD_dQOELMWA
(available one week)

**Comment by Dune-jr** [comment]
I can hear it. Good job! :)

**Comment by Fudgyking** [comment]
Oh ok now I can hear it, nice find lol

**Pull request merged**
