### PR TITLE
Replace existing CI services with GitHub Actions

### PR DESCRIPTION
**Pull request by axblk**
This adds a github actions workflow for building, testing and packaging teeworlds with cmake and bam on linux, macos and windows.
CircleCI, Travis CI and Appveyor are removed.
The created packages are uploaded as artifacts.
The cmake build uses ninja as generator.

### CODE REVIEW

**Comment by heinrich5991** [comment]
What is the rationale for removing the other CI services? Could you document what configurations we lose due to this?

I'd like to see the `make` backend tested for CMake so we don't accidentally break it. Additionally, it looks like you now run the Windows build with ninja instead of the native MSVS build system.

**Comment by axblk** [comment]
The workflow uses the same parameters for building like the other CI services. It is easier to have one workflow to test all systems (and build tools). In my opinion, maintaining several services is just extra work. For testing additional configurations or cmake generators one could just extend the build matrices.

I only chose ninja because it is faster. Using `make` and msbuild instead should not be a problem.

**Comment by heinrich5991** [comment]
Sorry for starting so negative. Thanks for working on this, e.g. having CI building artifacts would be awesome.

It it interesting to run the builds on the non-newest version so that we don't accidentally start depending on some behavior of a newer version. E.g. the circleci build currently runs on Debian stretch (oldstable), and tests that our build also runs with an old cmake version (3.7.2). Do you know whether something like this is also available for Github Actions?

**Comment by axblk** [comment]
All fine, I see your point. Removing test cases isn't a good idea, but I tried to cover all things that were checked on the other CI services.

Linux and MacOS are using make, and Windows Visual Studio as cmake generators now.
I also added Ubuntu 16.04 for testing cmake 3.5.

The test matrix for cmake is a bit more complex now, but you can easily add more configurations, generators, compilers, etc.

**Comment by heinrich5991** [comment]
Nice, thanks for adding the older configuration as well. This now covers the [cmake version (3.7) used by Debian oldstable (stretch)](https://packages.debian.org/oldstable/cmake).

**Pull request merged**
