### PR TITLE
Server broadcast

### PR DESCRIPTION
**Pull request by LordSk**
image
image
image

Server broadcasts appear at the bottom of the screen, and fade away after 10s. They can use different text colors with aspecial prefix: **^XXX**, with X = [0-9].
Examples: ^900 is full red, ^050 is half green.

This obviously can be abused quite a bit (just like chat), so there is an option to mute broadcasts on a given server, as well as globally (cl_show_server_broadcast).

This ended up being a lot more complex to implement than I expected, mostly because of the text api, which I hope we'll work on in the future. Also I only realized at the end that we had a *broadcast.cpp*. I can move the code over if this is an issue tomorrow, but for now, I'm going to sleep.

*Also thank you for the help testing, @Dune-jr*

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Yay nice to see broadcast back again! Even with colors o.O
But imo the black background looks weird because it is agian chopped of on both sides.
Also the text "server broadcast" is a bit distracting. I suggest removing the whole thingy under the broadcast.

removemepls


And is it possible to write multiple lines of broadcast or is it limited to one line at the bottom only?

**Comment by Zatline** [comment]
I like the idea with the gradient beneath it

**Comment by oy** [comment]
Coloured broadcasts are really annoying - shouldn't be there. Or disabled on default.

**Comment by Dune-jr** [comment]
> And is it possible to write multiple lines of broadcast or is it limited to one line at the bottom only?

You can do multiple lines. This is why that PR was submitted at 3am (:D) the text API needed a surprisingly large amount of work and fixes to write centered text.


I was part of the process so I'm biased, but I really like the gradient thing. The whole thing feels less rough than the old broadcast.

@LordSk didn't really show it here, but there is an option to mute broadcasts client-side on a server, a bit like chat muting.

Not sure what should be done with the colors idea.

**Comment by LordSk** [comment]
To clarify, you can't force multiple lines (yet), the text will auto-adjust depending on the content.

**Comment by fokkonaut** [comment]
Cool someone is supporting broadcast, not so cool are the colors and that the broadcast is on the bottom of the screen and not top. But whatever

**Comment by 1stDecadeTW** [comment]
> Cool someone is supporting broadcast, not so cool are the colors and that the broadcast is on the bottom of the screen and not top. But whatever

I think that bottom and coloured server broadcast is so convenient for the tw "tutorial" (maybe named as: "single player", "adventure mod", whatever) that could be implemented in next versions.

**Comment by LordSk** [comment]
image

- Added support for user defined lines (\n)
- Polished the bottom bar
- Added an option to enable colors (off by default, this is an opt-in feature)

The max is 3 lines, and whenever the broadcast takes more than 1 line, font size is reduced (as shown on the screenshot).

**Comment by ChillerDragon** [comment]
It looks beautiful!
Thanks for the good work c:
Can we get the font size a bit bigger? It looks almost like chat.

**Comment by Dune-jr** [comment]
No, @ChillerDragon. It would intersect with chat.

**Comment by Fisico** [comment]
i dont like the angled end of the gradient bar. is it possible to make it round?

**Pull request merged**
