### PR TITLE
Added tokens to the network and refactored master server code (please merge ;) )

### LINKED ISSUE #235: Teeworlds Slot user
There is a new program by xagels, He can take up slots in servers... He does it through "Stalling" Inbetween jooining and getting the message "max ip used" also it doesnt use ip's.

### PR DESCRIPTION
**Pull request by heinrich5991**
Summary
-------

Prevents ip spoofing of (hopefully) any kind:
* master server attack (see mailinglist)
* server flood attack
* session hijacking
* faking server info

Protocol change
---------------

The new network protocol header looks as follows:

    packet header: 11 bytes (15 bytes for connless)
      unsigned char padding[3]; // 24bit extra (must be 0x000000) to ensure compatiblity with the 0.5/0.6 protocol
      unsigned char version; // 8bit version (must be 0x01)
      unsigned char token[4]; // 32bit token (0xffffffff means none)
      unsigned char flags_ack; // 4bit flags, 4bit ack (0xff for connless packets)
      unsigned char ack; // 8bit ack (0xff for connless packets)
      unsigned char num_chunks; // 8bit chunks (0xff for connless packets)

      (unsigned char response_token[4];) // 32bit response token (only in case it's a connless packet)

Old packet header:

    legacy packet header: 3 bytes (6 bytes for connless)
      unsigned char flags_ack; // 4bit flags, 4bit ack
      unsigned char ack; // 8bit ack
      unsigned char num_chunks; // 8bit chunks

      (unsigned char padding[3];) // 24bit extra incase it's a connection less packet
                                  // this is to make sure that it's compatible with the
                                  // old protocol

Connection set up
-----------------
1. `CNetClient::Connect` is called
   This generates a client-side token which is only used for this connection.
   Then it sends a `NET_CTRLMSG_TOKEN` with its own token to the server in order to request a connection token.
2. The server receives a `NET_CTRLMSG_TOKEN`
   It uses `CNetTokenManager` to a create server-side connection token based on a salt which is changed every ten seconds and the client address.
   Then it sends this token with a `NET_CTRLMSG_TOKEN` message (which also includes the client connection token for authentication) to the client.
3. The client receives a valid `NET_CTRLMSG_TOKEN` with the server connection token and its own token. Because it gets the own token back, the client knows that no one spoofed the `NET_CTRLMSG_TOKEN` packet.
   It then proceeds in the normal connection process, sending the `NET_CTRLMSG_CONNECT` with both tokens and further packets with the own token, to verify that no one spoofed a client packet (might particulary be important for rcon commands).
4. The server can reconstruct the token it sent to the client, so it can verify the client. Since the seed changes every 10 seconds, the server compares the token it gets from the client with both the tokens generated from the current and the last seed.

Connless packet
---------------
1. `CNet*::Send` is called with an connless packet (NETSENDFLAG_CONNLESS).
   The Net* calls its `CNetTokenCache` which stores the packet and sends a token request (`NET_CTRLMSG_TOKEN`) to the server.
2. The server receives the token requests, and uses `CTokenManager` to create a IP-specific token, which it sends back to the client.
3. The client receives the token from the server, now `CTokenCache` sends the stored packet with the token to the server.
4. The server receives a connless packet with a token, now knowing that it comes from an IP which isn't spoofed.

Stateless packet
----------------
`CNet*::Send` is called with an stateless packet (NETSENDFLAG_CONNLESS|NETSENDFLAG_STATELESS). It just sends the packet, this behaves like the old connless packets.

See also #915.
Fix #235.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Should I rebase this?

**Comment by heinrich5991** [comment]
Should I rebase this? Got some time right now.

**Comment by prathje** [comment]
I am not sure if ip spoofing is being abused currently. But it is certainly a security problem for as long as one has the ability to create a fake server which collects user ips. So I would appreciate a rebase and be glad if this feature would be added in the next release.

**Comment by heinrich5991** [comment]
@prathje: @Oy said that he was going to look at this stuff soon, and I'm just asking whether I should rebase it for easier merging.

**Comment by oy** [comment]
No need to, already merged it locally - just had no time to finish it yet.

**Comment by oy** [comment]
Added.

**Comment by minus7** [comment]
Since this breaks compatiblity it should also use different DNS names to find masters (as said before here, and in #713). It's also a bit of a problem not being able to run 2 masters on one machine/ip.

**Comment by heinrich5991** [comment]
The version of the pull request does not break compatiblitly AFAIK. If it hasn't been merged completely, then this might be a problem. I guess you could implement a splitter that separates 0.6/0.7 and forwards it to the relevant master server on the same machine.

**Comment by minus7** [comment]
Well, if compatibility code is in then it doesn't work. But the splitter idea (which i of course had myself as well!) would work. I'd remove all compatibility code if any remains

**Comment by oy** [comment]
There's no compatibility code.

Simplest thing would be to use a different port - like done in the past.

**Comment by minus7** [comment]
Done in the past? When/where?
Any objections to using a version-specific subdomain for masters? Or even a SRV record (that can include port)

**Comment by Teetime** [comment]
For a simple and fast solution you could use the "ID" of the master as an offset to the port. For example
master1.teeworlds.com => 8201
master2.teeworlds.com => 8202 etc.

**Comment by minus7** [comment]
That doesn't really solve anything, it'd have to be version-dependent.

**Comment by oy** [comment]
>Done in the past? When/where?

In 0.3; used to be 8383.
>Any objections to using a version-specific subdomain for masters? Or even a SRV record (that can include port)

Would be good - including the port might be the best.

**Comment by minus7** [comment]
So we have four options here:
- ~~use SRV DNS records to point the client to ip & port of the master(s)~~ would require adding DNS library (not possible with the currently used getaddrinfo)
- reintroducing backwards compatibility
- ~~using a reverse proxy to redirect to the right master~~ overkill, an extra thing to maintain
- using a different port

I don't really like using a different, fixed port, so there's not many options left ;D
Does compatibility mean compatibility code in the network code outside of `mastersrv.cpp`?

**Comment by heinrich5991** [comment]
Yes, it would mean that, but I think it was just these few lines: https://github.com/heinrich5991/teeworlds/commit/1e723227f38e0ec871add4497ba3cd53a9738aae

**Pull request closed without merging**
