### PR TITLE
Remove remains of flow, fix 50 Hz effects timer, refactor

### LINKED ISSUE #2437: Decide what to do with CFlow
[`CFlow`](https://github.com/teeworlds/teeworlds/blob/master/src/game/client/components/flow.cpp) is effectively unused since 0.5. Only `Add` and `Update` are called. Neither `Get` nor `DbgRender` are used, making these calculations effectively useless. The related config var is commented out
`//MACRO_CONFIG_INT(ClFlow, cl_flow, 0, 0, 1, CFGFLAG_CLIENT|CFGFLAG_SAVE, "")`. Even then only being
> a test feature in the past - @oy 2011

I can see the use this could have, but then we should actually make use of it and not have it sitting around in an incomplete state.

Or it should just be removed, because having been unused all those years might be an indication that there isn't a good use for it, or the effects system on it's own works well enough.

### PR DESCRIPTION
**Pull request by Robyt3**
- Remove CFlow and it's commented out remains. Closes #2437.
- Fix how the 50 Hz effects timer was also 100 Hz.
- Remove duplicated code by putting effect speed in a variable.

### CODE REVIEW

**Comment by oy** [comment]
Would rather keep the flow stuff, might use it in the future.

**Comment by Robyt3** [comment]
It's been sitting around collecting dust for 8 years. Why not reduce the memory footprint of teeworlds, and only add it back once it's actually a fully fledged feature (if it ever gets to that point). We are using git anyway, so just keep the dead code in the git history instead of release builds? That's 32 * gameLayerWidth * gameLayerHeight bytes of RAM saved (1 MB on ctf5), as well as 4 * w * h floating point calculations (129600 on ctf5) per frame.

"Might be used in the future" != KISS

**Comment by oy** [comment]
The whole thing is already disabled (the init function isn't called), so no harm in keeping it in. So people are still able to work on it.

**Comment by heinrich5991** [comment]
Removing code should generally be applauded. You can always get the code back from the git repository. You wouldn't accept a pull request that adds dead code for a "far in the future" feature either.

**Pull request closed without merging**
