### PR TITLE
Add padding to dialog

### PR DESCRIPTION
**Pull request by masahiroCAN**
I added a right Padding to 3 dialogs ( delete skin, rename demo and delete demo). Here is a screenshot of one of them. 
screen shot 2019-03-03 at 11 37 19 pm

### CODE REVIEW

**Comment by Dune-jr** [comment]
- I'm not sure if I understand the scope of https://github.com/teeworlds/teeworlds/issues/2028. I imagined the text of those popups should be centered — like the others — instead of having some margin. 

- When undoing experimental changes, you can simply use `git reset HEAD~1` to undo the last commit. This way, you don't need to close/reopen PR when you want to make changes, and you can clean the commit history at will (you'll need to `git push -f` if already pushed).

**Comment by oy** [comment]
@Dune-jr 
Localized texts could be longer and then they'd overlap when rendering the text centered cause it doesn't work with multi lines.
So I guess some padding is alright.

**Comment by oy** [comment]
Added 1f5cb3bbb4c4ebcb02ecf505022ceb1a713c14db.

**Comment by Dune-jr** [comment]
> they'd overlap when rendering the text centered cause it doesn't work with multi lines.

ah, I see. didn't know

**Comment by oy** [comment]
Should probably be fixed.

**Comment by Dune-jr** [comment]
Agree. Opened https://github.com/teeworlds/teeworlds/issues/2049

**Comment by masahiroCAN** [comment]
Thank you for the feedback. So we want these dialogues to be center-aligned? is this how center-aligned multiple lines could look like? these are just random sentences. 

center-aligned
]

**Comment by oy** [comment]
Yeah, but that's a bigger issue #2048

**Comment by masahiroCAN** [comment]
Okay, I can take a look if this is something i can fix!

**Pull request closed without merging**
