### PR TITLE
Add console navigation shortcuts

### PR DESCRIPTION
**Pull request by ChillerDragon**
Adds shortcuts for local and remote console

ctrl-a cursor to start
ctrl-e cursor to end
ctrl-k delete from cursor to end
ctrl-u delete from cursor to start

### CODE REVIEW

**Comment by Dune-jr** [comment]
- Where are those shortcuts from? Some vim-like editor?

- Why should it be console-only? Text navigation should be consistent and not hardcoded in console.cpp imho

- There are already some functions for text navigation using ctrl, e.g. ctrl-backspace, ctrl-delete, ctrl-arrows. In general, code for this is located there:

https://github.com/teeworlds/teeworlds/blob/0c338f0e00e21cd01c8f4eddc88fc831d855e068/src/game/client/lineinput.cpp#L97-L113

**Comment by ChillerDragon** [comment]
@Dune-jr those shortcuts work on most unix like terminals I don't know how they are called axactly. But I think some terminal users might expect them in the console but nobody in the chat or else where.

**Comment by oy** [comment]
Agree with Dune that text navigation should be consistent. 
And there's already:
- "Pos1" - moves cursor to the start
- "End" - moves cursor to the end

**Comment by ChillerDragon** [comment]
> Agree with Dune that text navigation should be consistent.
> And there's already:
> 
>     * "Pos1" - moves cursor to the start
> 
>     * "End" - moves cursor to the end

Pos1 and End are tricky on keyboard without numpad. I also agree about things should be consistent. Thats why I expect every shell like enviroment to react consitent to those shortcuts. And I keep pressing them in tw console to then fallback to holding down a key for multiple seconds.

**Comment by ChillerDragon** [comment]
As mentioned by @Learath2 ctrl+a will be mapped to select all soon and in general I feel like this pr is not getting merged.

So I will close this pull request and use a fork instead ._.

**Pull request closed without merging**
