### PR TITLE
Remove whitespace in release script

### PR DESCRIPTION
**Pull request by ChillerDragon**
#hacktoberfest
 future employee pls don't fire me for shitty prs i did today

### CODE REVIEW

**Comment by Learath2** [comment]
Please label this invalid before merging, this is the kind of behaviour that made hacktoberfest opt-in this year.

**Comment by ChillerDragon** [comment]
image

**Comment by heinrich5991** [comment]
Idk, remove the hacktoberfest label again? It was added on request of @ChillerDragon wants to abuse this apparently.

**Comment by ChillerDragon** [comment]
Wait I requested it? xd also thats the kinda pr I put out now and then even before I knew hacktoberfest

**Comment by ChillerDragon** [comment]
as discussed on irc these kinds of fixes don't vibe well here, especially not during october.

Sorry for the inconvience guys

**Pull request merged**
