### PR TITLE
Fix dead-spec camera

### PR DESCRIPTION
**Pull request by axblk**

### CODE REVIEW

**Comment by oy** [comment]
Dead players shouldn't be able to have freeview so they can't inform teammates about players from the opposing team. It should be restricted to teammates and death position.
Maybe remove the death cam position and jump automatically to an alive player, dunno?

**Comment by Dune-jr** [comment]
@oy: Then this would have to be locked on the client-side too?
I'm a bit surprised it's a feature, since information doesn't sound so important to me in a survival game.

**Comment by nheir** [comment]
What about spectators ? They can help fellow players through different channel.

**Comment by oy** [comment]
@Dune-jr 
I think information about the position of an opponent is useful. And when you're out of ammo and low on health you probably go for a draw and run/hide. 

@nheir 
When spectators are seperated from clients I thought about a future feature where you can delay the data for spectators by a specific time(f.e. 5 seconds (adjustable)). So the spectators see the game with a delay and can't spoil the match.

**Comment by nheir** [comment]
Oh, is it reference somewhere else ? It looks like another big feature to implement.

**Comment by oy** [comment]
Dunno if there's an issue for it. But probably sth for 0.8 :)

**Comment by Dune-jr** [comment]
Right now the dead-spec camera just feels buggy though. In my opinion, we shouldn't cripple the UX with anti-cheat features until they are properly implemented on both sides (e.g. lock camera client-side).

**Comment by oy** [comment]
Yeah, has to be fixed in the client. You always had a fixed camera when you are dead.

**Comment by oy** [comment]
Fixed it here abdde05df7f93c5583444a96464db23a6692b4fb

**Pull request closed without merging**
