### PR TITLE
Cleanup hpp guards

### PR DESCRIPTION
**Pull request by ChillerDragon**
Finishes leftovers from
https://github.com/teeworlds/teeworlds/commit/e6f0318bdfa49bde503742c856c8415f9b2c8018

### CODE REVIEW

**Comment by ChillerDragon** [comment]
I just looked at the ending and renamed HPP to H but the path also changed

``TL_FILE_STRING_H`` -> ``BASE_TL_STRING_H``

Its still not very consistent because most files have no comment after #endif I personally like them but adding it in the whole code base still seems wrong.

**Comment by heinrich5991** [comment]
Import the script from DDNet and let it run on CI, probably the only way to make sure the header guards/comments will stay ok.

**Comment by ChillerDragon** [comment]
@heinrich5991 which one? This https://github.com/ddnet/ddnet/blob/master/scripts/check_header_guards.py ? Does not look like it checks comments.

> probably the only way to make sure the header guards/comments will stay ok

If we agree on removing the comments I also think it is unlikely that they will appear again.

**Comment by heinrich5991** [comment]
You could adjust it to check for comments, too.

**Pull request merged**
