### PR TITLE
Adjust eye colour when it is too close to body colour

### PR DESCRIPTION
**Pull request by LordSk**
#2323 
For now it forces black eyes for team skins, and adjust eye colour otherwise.

Some results:
image
image
image
image

Menu preview:
image

### CODE REVIEW

**Comment by oy** [comment]
Hm, that should be handled on the client-side like the black skin. The server shouldn't have any knowledge about that stuff, like skin parts.

**Comment by LordSk** [comment]
@oy Alright I'll see to that tomorrow then (if I find the time).

**Comment by oy** [comment]
@LordSk great 👍

**Comment by LordSk** [comment]
Alright done. I modified the tee preview in the settings as well to reflect the colour change (see edited post). A warning could also be added later.

**Pull request merged**
