### PR TITLE
Fix filesystem/IO with unicode filenames on windows

### PR DESCRIPTION
**Pull request by Robyt3**
It was previously not possible to load a map or really any file with a filename containing unicode, e.g. german umlauts. Console map completion with unicode was also broken. Similarly it was not possible to load, rename or delete a demo with a unicode name. Starting the game and loading the config was also broken with a unicode windows username.

Now all filenames are converted from multibyte to widechar on windows, and the correct functions and structs (with the `W` suffix) are used consistently.

The usage of pnglite is adjusted so the file handle obtained from `io_open` is reused instead of using pnglite's file methods that cannot handle unicode paths correctly.

Fix command line arguments containing unicode on windows, by adding the `cmdline_fix` function to system fix encoding of argv in-place.

Implement `fs_is_dir` smarter by using `GetFileAttributesW` on Windows.

Remove unused `fs_getmtime` that does not work with unicode on Windows in favor of the existing more generalized `fs_file_time`.

Replace unused and not working `IOFLAG_RANDOM` with working `IOFLAG_APPEND`.

### CODE REVIEW

**Comment by Robyt3** [comment]
@oy What was the reasoning for https://github.com/teeworlds/teeworlds/commit/2a570196ef7dd66f475a3379b9cc5b6abf915e09 ? Why make only the READ operation case sensitive? This only breaks some cases where demos specify a map name in different case, where it would be easier to load the map with different case name anyway for convenience.

**Comment by oy** [comment]
@Robyt3 can't remember. Probably some connection or map dl problem.

**Comment by Robyt3** [comment]
2a57019 causes map loading from demos to not work if you have a map with different capitalization already downloaded, for example if the author or a hoster of a map ever changed its capitalization. I didn't notice any issue with map downloading, as the existing map with different capitalization gets replaced by the new map with and without the commit. So do you want to keep it for legacy or remove it and maybe add back later if another issue arises?

**Comment by oy** [comment]
@Robyt3 isn't that also the case on case-sensitive operating systems? If the name of the map you have downloaded doesn't match case-sensitive wise to the one you need, it'll fail.

**Comment by Robyt3** [comment]
@oy True, it's better for consistency that way. This PR should now be ready for review.

**Comment by heinrich5991** [comment]
I can imagine the current code causing a problem:
1) Map with different capitalization than what is in the folder.
2) Client tries to re-download, replaces current map. Capitalization on disk stays the same unless you delete the old file beforehand.
3) Map still with different capitalization than what is in folder.
4) Client is confused that it cannot load the newly downloaded map.

I have not tested that this is actually a problem, but DDNet had this problem.

**Pull request merged**
