### PR TITLE
Add hotbar

### PR DESCRIPTION
**Pull request by EV3R4**
Adds a hotbar in the upper right corner and an option to disable it ("Show hotbar" in General).
Should I add myself to a credits section somewhere?

teeworlds_hotbar_reworked

### CODE REVIEW

**Comment by Dune-jr** [comment]
Gameplay changes should be greatly discussed before writing a pull request.

**Comment by EV3R4** [comment]
> 
> 
> Gameplay changes should be greatly discussed before writing a pull request.

How does it change gameplay, isn't it just UI?

**Comment by Dune-jr** [comment]
It significantly impacts gameplay/game design, just like a line of sight would.
By the way, we use CamelCase in the Teeworlds code: https://www.teeworlds.com/?page=docs&wiki=nomenclature

**Comment by jxsl13** [comment]
ew, brown background.

**Comment by EV3R4** [comment]
I will try to rework it to fit better into the game.

**Comment by EV3R4** [comment]
Reworked version:

teeworlds_hotbar_reworked

**Comment by TsFreddie** [comment]
> Gameplay changes should be greatly discussed before writing a pull request.

I actually disagree with @Dune-jr for calling this gameplay changes. In contrary, I think this change almost nothing to be worthwhile. You can see your current weapon from your tee, and the hot bar cannot represent whether you have the weapon nor doesn't it accurate convey the info about what will happen after `+nextweapon` and `+prevweapon`. These issues render the hot bar pretty much useless.

However, if we were to represent the weapon ownership info, this will become a gameplay change, and I agree we should discuss that with an issue first.

That being said, it looks like the hot bar will overlap with kill messages.

**Comment by Dune-jr** [comment]
This is in the game design realm. The game UI was designed with some precepts of minimalism that most games aren't concerned about.
This sort of basic HUD is a light implementation task, so there is a reason why matricks didn't go with it right away, and this should at the very least be discussed before jumping in the specifics of the code or the color of the background.

**Comment by jxsl13** [comment]
the new background looks better in the screenshot.

**Comment by ChillerDragon** [comment]
> the new background looks better in the screenshot.

yes

But im not sure about the feature in general who uses it?

**Comment by EV3R4** [comment]
> 
> 
> That being said, it looks like the hot bar will overlap with kill messages.

You're right, it does.
I didn't notice it because I mostly only tested in single player.

**Comment by Fisico** [comment]
I think such a UI element is long overdue but the placement is wrong because it overlaps with the kill messages and the elements are way too big for no reason.

Please have a look at my UI draft I did some time ago, 
It would be nice to toggle it via settings entry or console command.

For game types like survival it is key to know, that you have weapons. I was on quite a few survival servers where new players asked me where I get the weapons from.


image

**Comment by oy** [comment]
Agree with @Fisico , think we should discuss such a hud change in a new issue.

**Pull request closed without merging**
