### PR TITLE
Disable macOS accent menu Fix #1860

### LINKED ISSUE #1860: macOS shows char suggestions when pressing A longer
@oy as I mentioned in the chat the suggestions shows up while playing and pressing A too long. Actually I mean this:

bildschirmfoto 2018-12-13 um 22 51 24

In Teeworlds it is shown in the top-left corner of the game. It is not interrupting the gameplay at all but is still a visible bug.

I've been using the latest version of Teeworlds (0.7.1) and macOS 10.13.6.

P.S.: I love to see that teeworlds continues ❤️

### PR DESCRIPTION
**Pull request by Learath2**
SDL2 defines an `SDLApplication` which is the delegate that is used, which seems to do something to cause the accent menu not to appear. Problem is this seems to revert 6febd33 but I can't seem to find any issues.

It'd be great if you could take a look @oy

### CODE REVIEW

**Comment by oy** [comment]
@Learath2 
The problem was that when using the App it didn't find the data folder.

**Comment by Learath2** [comment]
@oy how do we get an App to compile? I couldn't really figure out how to create one

**Comment by oy** [comment]
@Learath2 
`scripts/make_release.py` call it from the tw main dir with `version` `plattform`

**Comment by ChillerDragon** [comment]
@Learath2 

alternative using cmake
```
mkdir build && cd build
cmake .. -DPREFER_BUNDLED_LIBS=ON
make package_default
```

which on macOS will result in the same as
```
mkdir build && cd build
cmake .. -DPREFER_BUNDLED_LIBS=ON
make package_dmg
```

**Comment by Learath2** [comment]
@oy I think this fixes the problem. We were only using the setupWorkingDirectory part of the SDLMain class and that entire file was preventing SDL from initializing the application properly.

If we need to do something in the delegate in the future we can employ method swizzling to hook into SDLAppDelegate (I've tested it and it works very well)

**Pull request merged**
