### PR TITLE
Add CJsonWriter

### PR DESCRIPTION
**Pull request by Robyt3**
I was just working on this when I saw the pull request about invalid json.

This adds a class to write valid and correctly formatted JSON more easily.

The format changes in minor ways to be more uniform. Example:

```
{
	"skin" : {
		"body" : {
			"filename" : "force",
			"custom_colors" : true,
			"hue" : 255,
			"sat" : 255,
			"lgt" : 0
		},
		"marking" : {
			"filename" : "coonfluff",
			"custom_colors" : true,
			"hue" : 161,
			"sat" : 255,
			"lgt" : 0,
			"alp" : 255
		},
		"decoration" : {
			"filename" : "twinbopp",
			"custom_colors" : true,
			"hue" : 64,
			"sat" : 255,
			"lgt" : 128
		},
		"hands" : {
			"filename" : "standard",
			"custom_colors" : true,
			"hue" : 16,
			"sat" : 133,
			"lgt" : 121
		},
		"feet" : {
			"filename" : "standard",
			"custom_colors" : true,
			"hue" : 17,
			"sat" : 129,
			"lgt" : 38
		},
		"eyes" : {
			"filename" : "standard",
			"custom_colors" : false
		}
	}
}
```

This also changes "custom_colors" to a boolean value. Parsing stays backwards compatible.

### CODE REVIEW

**Comment by heinrich5991** [comment]
I like this.

**Comment by heinrich5991** [comment]
It doesn't seem to do escaping of strings though.

**Comment by Robyt3** [comment]
True, for universal JSON serialization it should escape strings.

Do you know what's up with that test? I'm pretty sure I added the files to CMakeList.

**Comment by oy** [comment]
The name "BeginAttribute" is kinda strange when there's no corresponding end-function like for the others.

**Comment by Robyt3** [comment]
Hm, just `WriteAttribute`?

**Comment by oy** [comment]
Yeah probably better.

**Pull request merged**
