### PR TITLE
Add local console if statements (closed #2670)

### LINKED ISSUE #2670: advanced config syntax
I know its crazy but sometimes I feel an urge for basic if statements and variables in my config.
Things like this would be nice:

auth.cfg
```
if ui_server_address == "localhost"
  rcon_auth rcon
else
  rcon_auth crazy_secure_password
endif
```

config.cfg
```
bind x "exec auth.cfg"
```

So there is no need to add a new variable system. Just supporting comparison for the existing variables would be very useful already.

### PR DESCRIPTION
**Pull request by ChillerDragon**
I quickly hacked sumsin together its a bit crappy but it works as expected supporting if and else branches (no nesting and single condition only) in config and in interactive console (server and client).

[video showing interactive console](https://zillyhuhn.com/OpenTube/video.php?t=teeworlds_if_else_statements_pr2671.mp4)

### CODE REVIEW

**Comment by fokkonaut** [comment]
Just watch your gif, when entering the if> mode, it thinks you entered player_name alone so it prints its value again

**Comment by ChillerDragon** [comment]
closed by https://github.com/teeworlds/teeworlds/pull/2723

**Comment by Dune-jr** [comment]
Issues shouldn't be closed before the PR is merged. Merge commits can auto-close an issue.

**Comment by ChillerDragon** [comment]
> Issues shouldn't be closed before the PR is merged. Merge commits can auto-close an issue.

Yea that makes sense. But I can close a PR and keep the issue open if a new PR implements the feature based on the feedback from the issue right?

**Comment by Dune-jr** [comment]
@ChillerDragon Oh, my bad, I thought this was an issue that was closed by #2723

**Comment by ChillerDragon** [comment]
> @ChillerDragon Oh, my bad, I thought this was an issue that was closed by #2723

No wowwys mate <3 we all get confoosed at some point or the other

**Pull request closed without merging**
