### PR TITLE
Add window highlighting on chat messages

### PR DESCRIPTION
**Pull request by heinrich5991**
@cinaera Is this okay with you?

Thanks to DDNet team, specifically @def- and @cinaera for implementing this.

### CODE REVIEW

**Comment by heinrich5991** [comment]
See also #1278.

**Comment by heinrich5991** [comment]
Compilation tested on Windows, too.

**Comment by cinaera** [comment]
@heinrich5991 sure (:

**Comment by CytraL** [comment]
What do you think about using 'notify-send' on linux?
And perhaps is best only send "flash" when the window hasn't focus...

**Comment by oy** [comment]
Won't add plattform dependant stuff should be kept to the minimum and essential things, it's not multiplattform and Teeworlds isn't a chat-client.

**Pull request closed without merging**
