### PR TITLE
CHALLANGE -> CHALLENGE and mark as unused

### PR DESCRIPTION
**Pull request by ChillerDragon**
There is a typo in challange and both messages seem unused.

### CODE REVIEW

**Comment by heinrich5991** [comment]
LGTM.

**Comment by jxsl13** [comment]
Fixes a game breaking bug, must be emergency merged.

**Comment by ChillerDragon** [comment]
Force push also marked ``NETMSG_AUTH_START`` and ``NETMSG_AUTH_RESPONSE`` as unused.

**Comment by ChillerDragon** [comment]
``NETMSG_MAPLIST_ENTRY_REM`` is technically unused too trololol. But there is code there that could be called so I guess not annotating that is fine.

**Comment by ChillerDragon** [comment]
Another force push to also mark ``NETMSGTYPE_SV_EXTRAPROJECTILE`` (``CNetMsg_Sv_ExtraProjectile``) as unused

**Comment by heinrich5991** [comment]
It's used by old servers and old clients, I think.

**Comment by ChillerDragon** [comment]
> It's used by old servers and old clients, I think.

```
$ git log -S CHALLANGE
commit 72c06a258940696093f255fb1061beb58e1cdd0b
Author: Magnus Auvinen <magnus.auvinen@gmail.com>
Date:   Sat May 29 07:25:38 2010 +0000

    copied refactor to trunk

commit 3b086d616a9090f714c90c7985f10c5dc4bd5733
Author: Magnus Auvinen <magnus.auvinen@gmail.com>
Date:   Sun Sep 7 21:13:24 2008 +0000

    fixed threaded jobs
```

```
$ git show 3b086d616a9090f714c90c7985f10c5dc4bd5733 | grep -C 5 CHALLANGE
@@ -41,6 +41,9 @@ enum
        NETMSG_SNAPSMALL,               /* */
        NETMSG_RCON_AUTH_STATUS,/* result of the authentication */
        NETMSG_RCON_LINE,               /* line that should be printed to the remote console */
+
+       NETMSG_AUTH_CHALLANGE,  /* */
+       NETMSG_AUTH_RESULT,             /* */
 
        /* sent by client */
        NETMSG_READY,                   /* */
@@ -49,6 +52,9 @@ enum
$ git show 72c06a258940696093f255fb1061beb58e1cdd0b | grep -C 5 CHALLANGE
-       NETMSG_SNAPSMALL,               /* */
-       NETMSG_INPUTTIMING,             /* reports how off the input was */
-       NETMSG_RCON_AUTH_STATUS,/* result of the authentication */
-       NETMSG_RCON_LINE,               /* line that should be printed to the remote console */
-
-       NETMSG_AUTH_CHALLANGE,  /* */
-       NETMSG_AUTH_RESULT,             /* */
-
-       /* sent by client */
-       NETMSG_READY,                   /* */
-       NETMSG_ENTERGAME,
--
+       NETMSG_SNAPSMALL,               //
+       NETMSG_INPUTTIMING,             // reports how off the input was
+       NETMSG_RCON_AUTH_STATUS,// result of the authentication
+       NETMSG_RCON_LINE,               // line that should be printed to the remote console
+
+       NETMSG_AUTH_CHALLANGE,  //
+       NETMSG_AUTH_RESULT,             //
+
+       // sent by client
+       NETMSG_READY,                   //
+       NETMSG_ENTERGAME,
```

**Comment by heinrich5991** [comment]
Yea, I meant extraprojectile, thanks for researching that.

**Pull request merged**
