### PR TITLE
Make the ingame browser an icon

### PR DESCRIPTION
**Pull request by Dune-jr**
https://github.com/teeworlds/teeworlds/issues/2318

- Fixed shadow (22541c3)
- Made ingame browser an icon (22541c3)
- Added two icons for a better on-hover effect (6d0782a)

Possibly:
- Replace "Settings" by the settings icon (dba7704)

Either merge PR or cherry-pick 22541c3 6d0782a

### TODO
- [x] TODO: a black version of the globe icon

### Screenshots
image
image
(has a size issue) e: maybe a spacing one too

### CODE REVIEW

**Comment by fokkonaut** [comment]
While at it, we should add an Editor icon, like in DDNet, there it is a pencil.

**Comment by Dune-jr** [comment]
> While at it, we should add an Editor icon, like in DDNet, there it is a pencil.

I imagine it opens the current map when ingame?

**Comment by fokkonaut** [comment]
No, just the editor, like ctrl+shift+e

**Comment by Sonix-** [comment]
browser_icon

**Comment by Dune-jr** [comment]
Updated PR
image

**Pull request merged**
