### PR TITLE
Allow vote caller to cancel his own vote

### LINKED ISSUE #1432: Add possibility to allow vote caller to cancel his own vote

### PR DESCRIPTION
**Pull request by Zwelf**
Closes #1432 
The vote caller can abort his vote for the first 10 seconds.

### CODE REVIEW

**Comment by pielover88888** [comment]
Doesn't this need client-side support? From what I can see this only modifies the server?

**Comment by heinrich5991** [comment]
From what I can tell, it allows you to use f4 to cancel your vote.

**Comment by Henningstone** [comment]
Since not voting is equals to voting "no", I must agree to heinrich.

@pielover88888 Like Zwelf implemented it, it closes the whole vote when the vote caller himself presses f4 within the first 10 seconds after opening it, so no extra client-side support needed.

**Comment by oy** [comment]
Added.

**Pull request closed without merging**
