### PR TITLE
Match quick search against game type (closes #2275)

### LINKED ISSUE #2275: Server browser should also match searches against gametypes
This would make quickly searching for a gametype more convenient. Surely when one searches for `CTF`, it is reasonable to display all servers with a CTF gametype. The gametype string should be highlighted in blue.
It already works for maps.

Based on a suggestion from @fokkonaut

### PR DESCRIPTION
**Pull request by Robyt3**
screenshot_2020-01-07_00-51-14

### CODE REVIEW

**Comment by fokkonaut** [comment]
Do we want to remove the gametype filter on the right now?

**Comment by Robyt3** [comment]
I think it's distinct enough from the more coarse quick filter, as it does exact matches and allows multiple filters instead.

**Comment by heinrich5991** [comment]
> Do we want to remove the gametype filter on the right now?

Please don't, quick search doesn't allow searching for multiple terms right now.

**Comment by Dune-jr** [comment]
Agree, this can still be useful to set up filter sets.

**Pull request merged**
