### PR TITLE
Added download script

### PR DESCRIPTION
**Pull request by Zwelf**
Added a download script to download automatically SDL2 and freetype.
Added them to the gitignore.
Someone could add this to bam.lua.

### CODE REVIEW

**Comment by Henningstone** [comment]
This finally closes #1275, thank you, I waited for something like this :)
Have a look at your fork of teeworlds, I made a pull request to add it to bam.lua and fixed/improved a few things :)

**Comment by Zwelf** [comment]
@Henningstone The download of the SLD2.dll and freetypes.dll is not working correctly, because the bam.lua doesn't start the download.py.

**Comment by Henningstone** [comment]
Mmmh.. this is actually a problem. I determined it a bit more precisely by analyzing what happens while building an what doesn't:

- The two lines above it a being run -> Problem is in the `AddJob`
- I don't know for sure how bam works internally, but I guess that the problem is how AddJob() works:

** AddJob(a,...,b) executes b if something needs file a: **
```Lua
AddJob( [file which might be required to build], [Description to display in console], [command to execute if the given file *is* being required] )
```
** We call: **
```Lua
AddJob(cur_builddir .. "/" .. "SDL2.dll", "Downloading SDL2.dll for " .. cur_arch .. "/" .. cur_conf, dl .. " SDL2.dll")
```
Now just connect these two and count one by one together:
OF CAUSE nothing requires a dll while *building* as they are required to *run*!! So it would never run the command to download it!


Conclusion: We need to think of something else........


// EDIT: I will anyway push a commit to fix a very dumb mistake.

**Comment by Henningstone** [comment]
Ok, now I finally got it to work! The mistake was that I didn't add any dependency in the bam.lua, so it couldn't work properly. That's fixed now.

For downloading the dll's, what I did is rather more than a workaround, but it works now. They are being downloaded together with the includes until we thought of something better. (as described above)

**Comment by heinrich5991** [comment]
You could make `SDL2.dll` a dependency of the resulting binary `teeworlds`.

**Comment by Henningstone** [comment]
Of course I thought of this too, but it won't work since there is no Job for the binary (it is made by `Compile(...)` and `Link(...)` as far as I am right)
``bam.lua:494: add_dependency: couldn't find node with name 'build/x86/debug/teeworlds.exe'``

I also thought of making it a dependency for any other random file which belongs to the client by just doing AddJob(); AddDependency(), but this seems a bit hackish to me and additionally might not work.

**Comment by Zwelf** [comment]
Superseded by #1347.

**Pull request closed without merging**
