### PR TITLE
Add server browser from ingame

### PR DESCRIPTION
**Pull request by nheir**
Proposal for #1552 
Use same mechanism as settings from ingame menu.

### CODE REVIEW

**Comment by 1stDecadeTW** [comment]
How should ingame browser look like? Maybe these features should be add:
- Recent servers (history): it would be useful a green and grey indicator that let the user know if the server is online.
- Friends indicator.
- More Ideas?

**Comment by nheir** [comment]
Do this features are the same as usual server browser ?

**Comment by Sonix-** [comment]
If we are going to add an ingame browser then it should look the same as the main one or even look simplier.

**Comment by Dune-jr** [comment]
If squatting players slots is the main concern, I would propose to lock it to spectator-only. Ideally, this could come along/depend on #1580?

**Comment by fokkonaut** [comment]
Would be cool to see this one, very usefull and nice to have. Doesnt harm anyone

**Pull request merged**
