### PR TITLE
Add emotional tees

### PR DESCRIPTION
**Pull request by Panquesito7**
When a player uses an specified emote (such as happy) his face will change to happy.
Same with the other emoticons.

### CODE REVIEW

**Comment by fokkonaut** [comment]
First of all, that should be a character variable.
But this should not get added to vanilla, I talked to some people about this long ago already and they said the eyes were to symbolize kills/damage/ninja etc in vanilla

**Comment by Panquesito7** [comment]
> But this should not get added to vanilla

I thought of making it an option and be disabled by default, but it's still there, anyway.

**Comment by ChillerDragon** [comment]
@Panquesito7 the issue to this feature already got closed :/ 

https://github.com/teeworlds/teeworlds/issues/1663

**Comment by oy** [comment]
These emotes display gameplay events like kills, damage taken etc. and should not be used otherwise. As that might be confusing.

**Pull request closed without merging**
