### PR TITLE
reading server list from server ip cache - first commit

### PR DESCRIPTION
**Pull request by winterismute**
Should implement #1154

### CODE REVIEW

**Comment by Henningstone** [comment]
Are you still working on this? I had recently some time and so I started off with testing you stuff.
Unfortunately it seems not to work as it is supposed to:
- There are actually two remote 0.7 servers online and registered at the masterserver (at least when I tested it).
- The file ``servercache.cfg`` is being created and overridden with empty contents (so *nothing*) at gamestart and whenever the serverlist catches any remote server on reloading.

By the way, there is no console output from ``LoadServersFromFile()``, so it doesn't return -1 (not even when the file isn't existing).

Does this work for you or have I missed some important point?

**Comment by winterismute** [comment]
Hi Henningstone,
Glad you had time to try this out. I would be happy to try to complete this feature, although in these days I don't have much time, but I will find it.
Only one thing: from a master checkout, is there anything I have to do in order to receive a list of servers? So that I can debug properly.

**Comment by Henningstone** [comment]
You mean how to receive a full *list* of servers from the remote masterserver? Or how to receive all the servers to your local masterserver? Sorry, but I didn't get the actual question...

**Comment by oy** [comment]
fixed by a47f9faaf0480dbbaee24ad32caa7c49c44e3d38

**Comment by Dune-jr** [comment]
Cool to see that old PR merged. Thanks for the work, @oy!

**Pull request closed without merging**
