### PR TITLE
Fix RenderHSLPicker() arg naming

### PR DESCRIPTION
**Pull request by ChillerDragon**
Use ``CUIRect MainView`` in header matching the .cpp implementation

https://github.com/teeworlds/teeworlds/blob/26d24ec061d44e6084b2d77a9b8a0a48e354eba6/src/game/client/components/menus_settings.cpp#L64

### CODE REVIEW

**Comment by jxsl13** [comment]
I love it.

**Comment by heinrich5991** [comment]
To automate this kind of error detection, use clang-tidy, e.g. like here: https://github.com/ddnet/ddnet/blob/14927684eb078615c7eab8841c7043e0d063d6b3/.github/workflows/clang-tidy.yml.

**Comment by ChillerDragon** [comment]
> To automate this kind of error detection, use clang-tidy, e.g. like here: https://github.com/ddnet/ddnet/blob/14927684eb078615c7eab8841c7043e0d063d6b3/.github/workflows/clang-tidy.yml.

Yea I catched that using clang tidy. I [once tried](https://github.com/ChillerDragon/teeworlds/tree/pr_ddnet_clang_format) to get ddnets clang tidy config running for teeworlds. But rage quitted on macOS compliation not working anymore ._.

**Comment by heinrich5991** [comment]
Note: clang-tidy is something different from clang-format.

**Pull request merged**
