### PR TITLE
Implement layer saving. Fix #2503

### LINKED ISSUE #2503: [Editor2] Fix map saving
Fix the function `CEditorMap2::Save()`.
Make it as complete as the old editor.

### PR DESCRIPTION
**Pull request by Learath2**
Fixed up the save function, seems to save/load just fine.

### CODE REVIEW

**Comment by LordSk** [comment]
The group saving section needs to use m_aGroupIDList to keep the proper order. m_aGroups is just the data, unordered.

**Comment by Learath2** [comment]
Also got the variable names consistent, it was hard to read.

**Comment by Learath2** [comment]
Actually, I think I got that one completely wrong. It's tough to think about the two semi independent sets of ids

**Comment by Learath2** [comment]
Okay this time it actually makes sense when I read it. @LordSk take a look now :P

**Pull request merged**
