### PR TITLE
Add prediction for other players

### PR DESCRIPTION
**Pull request by Piepow**
## Changes
- Add `cl_predict_players` option for predicting other players (off by default)
  - Similar to antiping from DDNet client
- Hooks, nameplates, and flags are rendered using the predicted positions
- Removed prediction error checking

## Things to do in the future (not in this PR)
- Predict actions on other tees
  - Currently when you hammer another tee with `cl_predict_players` on, the force on the other tee isn't predicted
- Predict grenade jumps
- Projectile prediction (for grenade, shotgun, pistol)

### CODE REVIEW

**Comment by Dune-jr** [comment]
Related: #2461, #1409

**Comment by fokkonaut** [comment]
Please make options for the weapons, on modded servers (such as ddrace) shotgun for example is not using bullets, but a laser instead.

**Comment by fokkonaut** [comment]
DDNet predicts projectiles by having entity classes on the client side, maybe entities should be shared code in the game directory?

**Comment by ChillerDragon** [comment]
Awesome :) thanks for looking into the long awaited prediction feature!

Oh btw please use tw code style:

``if(`` instead of ``if (``

```
}
else
{
```

instead of ``} else {``

**Comment by fokkonaut** [comment]
I suggest renaming all "Should..." functions, something simple like `UsePredictedChars` or `PredictChars` is enough

**Comment by fokkonaut** [comment]
Also, maybe you should add another function to get the character position, which checks for predicted or unpredicted within that function, then you dont need all of the if elses for postions

**Comment by axblk** [comment]
So far, all similar attempts were rejected because it does not work properly. However, there is a huge demand for something like this, so in my opinion it's time to add such a functionality (disabled by default).

The prediction for other players cannot work reliably since we don't know their input, but especially with a high ping, this experience can still be better than having your own tee out of sync with the rest of the game-world.
To have the tees in sync with the flying projectiles, this might be added as well:
https://github.com/ddnet/ddnet/blob/cf069c0c514772a8f23fcc25dc55861eaa4e3d47/src/game/client/components/items.cpp#L54-L58

I think this very basic "antiping" version would be okay, but anything beyond that should go into custom clients. Predicting the actual firing of weapons and the effect of projectiles (e.g. rocket jumps), means simulating the whole gameworld on the client side, which requires a lot duplicate or shared code. In addition to problems like merging the local and the server gameworld, this would also lead to conflicts with mods that change the behavior of entities. Even for custom clients this should be limited to default gametypes, or the server should have the possibility to disable it.

**Comment by Piepow** [comment]
@fokkonaut 

> Please make options for the weapons, on modded servers (such as ddrace) shotgun for example is not using bullets, but a laser instead.

This PR probably won't include prediction for projectiles, but thanks for the info

> I suggest renaming all "Should..." functions, something simple like UsePredictedChars or PredictChars is enough

The "should" makes it clear that the function only checks for a condition, and there's already another function called `UsePredictedChars`.

> Also, maybe you should add another function to get the character position, which checks for predicted or unpredicted within that function, then you dont need all of the if elses for postions

I was going to, but there are some cases where I need the `CNetObj_Character` objects instead of just the position. Specifically in `RenderPlayer()` and `RenderHook()`, where I call `UsePredictedChar`.

**Comment by Dune-jr** [comment]
I +1 @axblk in that it is a very high-demand feature, so it would make sense to spend effort and add technical debt even for a limited version of this improved prediction.

**Pull request merged**
