### PR TITLE
Add option to disable background maps; reorganize menus a bit

### PR DESCRIPTION
**Pull request by Dune-jr**
Should help with #1566 and #1671

image
image
image

### CODE REVIEW

**Comment by Dune-jr** [comment]
We could go further and add a Theme dropdown list somewhere to help with #1566 and #1668 :
image

But this is bloating an already loaded General menu, and I would like to move this kind of option to some sort of advanced tab (see #1587). However, I still haven't received any suggestion on where this could be put (there is no room on the top bar).

Use horizontal tabs as we use to? Or hide it under some sort of [+] button/dropdown somehow?

Ideally, I would like to not put this option at all and just randomly cycle between maps. However, this would only fix the issue #1566 if the jungle map was severely simplified/reworked or removed - but that's quite a big design decision.

**Comment by Sonix-** [comment]
Perhaps add an option like the chat display one, toggle options “Display menu: none/default(jungle)/heavens”

**Comment by oy** [comment]
People can use any map they want as background map. Just put it in data/ui/ and set cl_menu_map to it. An theme selector might be pretty useful for that.

**Comment by Dune-jr** [comment]
This would probably require the maps to be put in a specific subfolders so that they can be listed (or list all the .map in data/ui/?)

**Comment by oy** [comment]
All maps in data/ui/ are background maps. ***_day/***_night for the day/night circle.

**Comment by Dune-jr** [comment]
@oy yeah, I'll make a separate issue

**Pull request merged**
