### PR TITLE
Fix laser rendering bug due to floating point precision error

### PR DESCRIPTION
**Pull request by cinaera**
This PR applies the patch from #1157

### CODE REVIEW

**Comment by heinrich5991** [comment]
\o/

Looks good to me.

**Comment by oy** [comment]
Won't add - it should be fixed by removing the floating point tick timers.

**Comment by heinrich5991** [comment]
Not sure why you closed this, the only float here is IntraTick and this is naturally a decimal number.

**Comment by oy** [comment]
I'm referring to the general float timers here https://github.com/teeworlds/teeworlds/blob/master/src/engine/client.h
Using float is pretty bad, next problem is just around the corner - these should all be ints.

**Comment by heinrich5991** [comment]
`GameTick()` and `m_StartTick` are both ints (correctly), and `IntraTick` is a float between 0 and 1 (correctly too, unless you want to use fixed-point numbers), no floating point problems here.

**Comment by oy** [comment]
All the general timers should be ints, it should not mix floats and ints.
It's a general thing not specific for this bug which is just one impact.

**Comment by heinrich5991** [comment]
Can we add this patch? This is clearly doing the right thing for this place (subtracting the integers first, then adding the sub-second precision with floats).

It just came up today on Discord again.

**Pull request closed without merging**
