### PR TITLE
Change alignment and size of the browser columns

### LINKED ISSUE #1789: Realign the columns in the serverbrowser
This is the current serverbrowser:
screenshot_serverbrowser

The text of each column is centered. For large data this is difficult to read.
To increase the readability, the columns should be realigned:
- plain text of different length should be left aligned
- text and icons of same length can be centered (thought it doesn't change anything then)
- numbers should be right aligned

Doing so, it will result in something like that:
screenshot_serverbrowser_aligned

Putting the readability aside, it is even more consistent. Most other text is not centered. Just take a look at the names of the scoreboard on the right side.

### PR DESCRIPTION
**Pull request by Dune-jr**
Closes #1789 

image

In doing so, the scrollbar got all the way up, that may be undesired, not sure.
The scrollbar used to be displayed *on top* of the browser entries. That doesn't work with right-aligned ping.

I adjusted the column alignment too, probably for the best.

### CODE REVIEW

**Comment by oy** [comment]
The headers look a bit odd. Maybe showing a box with less alpha when they're not selected and have them centered looks better.
Server names could be moved more to the left.
Centered player number probably look better too. Maybe use "%02d/%02d" for the text?
The ping numbers should have a little space to the right border.

**Comment by oy** [comment]
> 
> > Server names could be moved more to the left.
> 
> There is the lock and friend icons on the left iirc

The lock is left of the difficulty icon.

>
> > The ping numbers should have a little space to the right border.
> 
> That's on purpose:
> https://github.com/teeworlds/teeworlds/pull/1894/files#diff-3287b2addb72598cfece115cfba5ded8R926
> 
> Otherwise they glitch a bit. I can make a screenshot later

Ok. But on the screenshot on top they touch the border when the column is selected.

**Comment by Dune-jr** [comment]
> > > The ping numbers should have a little space to the right border.
> > 
> > 
> > That's on purpose:
> > https://github.com/teeworlds/teeworlds/pull/1894/files#diff-3287b2addb72598cfece115cfba5ded8R926
> > Otherwise they glitch a bit. I can make a screenshot later
> 
> Ok. But on the screenshot on top they touch the border when the column is selected.

Ah, I misunderstood, I thought you wanted *less* space. Alright then.

**Comment by Zatline** [comment]
- ping looks a bit meh so close to the scrollbar I would keep it centered or aligned to the opposite side or give it some offset perhaps? 
- huge gap between server and type looks a bit odd as well could need some balance  

but the rest looks good I like it a lot 👍

**Comment by Sonix-** [comment]
Hmm usually scrollbars are applied only to the scrollable areas (like it is now), it's weird to apply it on the whole window and misleading.

**Comment by Dune-jr** [comment]
> Hmm usually scrollbars are applied only to the scrollable areas (like it is now), it's weird to apply it on the whole window and misleading.

Does that look better to you, @Sonix- ?
image

**Comment by Dune-jr** [comment]
@oy Center align:

image

Is the map column good or concerning?


Also, I think %02d/%02d doesn't work very well:
image

**Comment by Sonix-** [comment]
Well, I prefet the scrollbar as it is now. It follows what I've said in my previous reply

**Comment by Dune-jr** [comment]
@oy
- [ ] The headers look a bit odd. Maybe (1) showing a box with less alpha when they're not selected 
- [x] (2) and have them centered looks better.
- [ ] Server names could be moved more to the left.
- [x] Centered player number probably look better too. Maybe use "%02d/%02d" for the text?
- [x] The ping numbers should have a little space to the right border.
@Zatline
- [x] ping looks a bit meh so close to the scrollbar I would keep it centered or aligned to the opposite side or give it some offset perhaps?
offset given
- [ ] huge gap between server and type looks a bit odd as well could need some balance
@Sonix-
- [x] Hmm usually scrollbars are applied only to the scrollable areas (like it is now), it's weird to apply it on the whole window and misleading.

**Pull request merged**
