### PR TITLE
Fixed button fade getting stuck in some situations

### LINKED ISSUE #1614: In ingame menus, sometimes, all buttons are highlighted as if they were all hovered (#1534 split 4/4)
I've experienced this bug a lot but was not able to reproduce it recently, might have been fixed?

### PR DESCRIPTION
**Pull request by LordSk**
Fixes #1614.

### CODE REVIEW

**Comment by Zatline** [comment]
Important quality of life improvement good job!

**Comment by oy** [comment]
It shouldn't call time_get all the time. Pretty heavy call and this gets executed a lot each frame.

**Comment by LordSk** [comment]
https://github.com/teeworlds/teeworlds/commit/b939d3822882c5061f5e3ddfb3fc3b13b116fe24#diff-c54ea30d8c95814c33b60fe2e04a9ef3R1488

I removed the reset of m_LocalStartTime and to my knowledge it shouldn't affect the game, but I've been wrong before.

**Comment by oy** [comment]
I think it's used for the envelope animation. There are synchronized ones that use the game tick and ones that start when you join a server.

**Comment by Dune-jr** [comment]
Is time_get really a heavy call? I think it's used often

**Comment by oy** [comment]
Would add a variable, that just updates once for a rendering call and use that instead - similar to m_LocalStartTime.

**Comment by LordSk** [comment]
Envelope time was not being reset (even before my changes), so I fixed that. And the editor was unusable due to wrong mouse world position; fixed as well. The rest of LocalTime() usage is independent of server join, so it should be fine like this.

**Pull request merged**
