### PR TITLE
Ignore _test.exe (generated by win build)

### PR DESCRIPTION
**Pull request by ChillerDragon**

### CODE REVIEW

**Comment by ChillerDragon** [comment]
I have no idea whats going on with the circleci again ._.
But i guess its not related to this pr

**Comment by oy** [comment]
Huh? It doesn't create a _test.exe.

**Comment by fokkonaut** [comment]
huh for me it also does

**Comment by oy** [comment]
Well, that's odd. Will look into that.

**Comment by oy** [comment]
Should probably propose it to bam then.

**Comment by oy** [comment]
Think so.

**Comment by Dune-jr** [comment]
@oy Shouldn't this be hotfixed in teeworlds, waiting for a bam fix?
At least a .gitignore

**Pull request merged**
