### PR TITLE
Fix server&friend browser spacing and scrolling

### LINKED ISSUE #1594: server browser scrollbar
The scrollbar in the server browser doesn't work correct. Empty lines at the bottom.

### PR DESCRIPTION
**Pull request by Dune-jr**
This very painful bugfix closes #1594.
There is now a proper amount of spacing at the end of the server browser, friends list, scaling with the # of filters. Arrow scrolling (ugh) has also been fixed.

### CODE REVIEW

**Comment by oy** [comment]
Looks like you can't move to the next frilter with arrows anymore?

**Comment by Dune-jr** [comment]
> Looks like you can't move to the next frilter with arrows anymore?

Was that feature ever working? I tried but never could make it work, so I reverted it to server-to-server.
Isn't it better that arrows move from server to server than filter to filter, either way?

**Comment by oy** [comment]
They move from server to server yeah. But when you reached the end of a filter you jumped to the next one.
f.e. from the bottom entry of your actual filter to the top entry of the next filter.
It used to work sometime, maybe it got broken again.

**Comment by Dune-jr** [comment]
Got it, @oy . I'll look into that.

**Comment by Dune-jr** [comment]
@oy The thing is though, the code to switch from a filter to the next one only does so if that filter is also expanded. It is currently impossible to expand two filters at once, so it is dead code.

**Comment by LordSk** [comment]
You should be able to expand several filters at once. If like CTF and DM on monday, I can expand both these filters instead of creating a "monday" filter.

**Comment by nheir** [comment]
I second this

**Comment by oy** [comment]
@Dune-jr 
Then maybe some other other key should be used to "jump" to the next/previous filter - so you are able to navigate entirely with the keyboard?

When your're able to expand multiple filters and you have lots of servers(~1000 in total like 0.6) it gets really hard to navigate, find smaller filters etc.

**Comment by Dune-jr** [comment]
Sounds good, @oy. Any idea for such a key? Ctrl+up/down maybe?

**Comment by oy** [comment]
@Dune-jr 
Yeah, Ctrl+up/down sounds good to me.

**Comment by Dune-jr** [comment]
Done.
That scrollbar code was a pain. I tried to make it a bit more readable.

**Pull request merged**
