### PR TITLE
Use str_length

### PR DESCRIPTION
**Pull request by ChillerDragon**

### CODE REVIEW

**Comment by jxsl13** [comment]
what's the point of this?

**Comment by ChillerDragon** [comment]
> what's the point of this?

If str_length is not used what is it its point? Trying to apply the same changes as in ddnet to keep things somewhat similar https://github.com/ddnet/ddnet/pull/3881

**Comment by jxsl13** [comment]
Learath2's point in that issue being not to use libc functions outside of system.c/h.
Your point being use functions because they exist?
I wonder how many more cases there are where implemented functionality is not used.

**Comment by Robyt3** [comment]
The main point is consistency. Other functions in `system.c` already use `str_length`, so it should be consistenly used everywhere there. While it isn't really relevant in this case, in general this would make it easier to change the implementation (using something else than `strlen`).

**Pull request merged**
