### PR TITLE
fix #541 : remove weak hook using

### LINKED ISSUE #541: Different hook strength
From drUncreative:

Tees have different strength of hook.
Here is a demo:
http://teedb.info/index.php?section=demos&id=21

https://github.com/oy/teeworlds/issues/closed#issue/530

### PR DESCRIPTION
**Pull request by nheir**
Use SaturateAdd after summing all the dragging velocity

### CODE REVIEW

**Comment by heinrich5991** [comment]
Please use descriptive variable names. `InteractVel` does not specify that only **hook** velocity deltas go in there, `IgnoreInteractVel` does not specify that it is only going to be ignored **for the next tick**.

`CCharacterCore::Move` is not the appropriate place for changing the velocity for things that happened in the tick. It should only move the tee.

This change can only be merged in the next major version bump as this changes network code.

**Comment by fokkonaut** [comment]
I'd rename the function to AddHookDragVel, and I'd also reset the var in this function, just at the end. So you could remove the reset function

**Comment by fokkonaut** [comment]
And why dont we need it while firing ninja? was it like that before?

**Comment by nheir** [comment]
> I'd rename the function to AddHookDragVel, and I'd also reset the var in this function, just at the end. So you could remove the reset function

I used the Reset function to set this additional velocity to  whatever the weapon.

> And why dont we need it while firing ninja? was it like that before?

I noted that the function `HandleWeapon`->`HandleNinja` changes the position of the Tee itself, overriding the velocity so that client doesn't predict stuff. 
https://github.com/teeworlds/teeworlds/blob/a60ab8d328eb000c5fc579be84e8abf95f35b2df/src/game/server/entities/character.cpp#L150-L155

Since this is taking account in Tick, depending on the character order, the players' hook have either no effect or a small effect on the speed and the position.
I chose no effect, since it's easy to make it fair, but I don't claim it is the good choice.
Is the trajectory of a ninja only depending on the initial position and direction ? or do/should other entities and hooks have an effect on this trajectory ?

Since the position is also updated by `HandleNinja`, there is still a difference when hooking a moving ninja.

And I realize that the players hit by a ninja isn't fair either.

**Comment by heinrich5991** [comment]
It looks like the hook code is only in the server side now. Have you tested hook interactions in the client side? The code is also used there (which is why it's a protocol change AFAICT).

**Comment by oy** [comment]
The current prediction is broken anyway. The order of the character handling differs between client and server.
So don't see a problem with adding without a major release.

**Comment by ChillerDragon** [comment]
yikes

**Pull request merged**
