### PR TITLE
Color picking for editor

### PR DESCRIPTION
**Pull request by msiglreith**
Added some color picking features for the editor: eyedropper/pipette and HSV color picker
(requested by @Sonix-).

Pipette is implemented by reading pixels from the current backbuffer, which involves CPU-GPU synchronization, but the performance penalty is neglectable.

(Includes cleanup and refactoring in some places)

Any feedback is welcome!

### CODE REVIEW

**Comment by Sonix-** [comment]
Nice work BeaR! :)
This feature surely makes tile/quads recoloring much quicker and easier and more accurate. :+1:

**Comment by nzyuzin** [comment]
Is colour picking the same as in https://github.com/ddnet/ddnet/pull/291?

**Comment by msiglreith** [comment]
@nzyuzin yes, the color picker is based on my old implementation for ddnet but I fixed up some stuff (cleanup and picker feels more responsive)

**Comment by nzyuzin** [comment]
But why won't you show any screenshots? \o/

**Comment by oy** [comment]
Added.

**Pull request closed without merging**
