### PR TITLE
Align voting control UI, hide vote after time elapsed, refactoring

### PR DESCRIPTION
**Pull request by Robyt3**
Implementation:
- Add VOTE_CHOICE_NO, _PASS, _YES constants to protocol and use them instead of the magic values
   - These also replace the VOTE_ENFORCE_* constants in CGameContext.
- Add CUI::CORNER_NONE for better readability instead of passing 0.
- Remove voting `RenderBars` parameter and implementation to render number of votes as text, as it's unused.
- Use size constants for vote option description and command where applicable.
- Rename some variables and methods.
- Encapsulate some of the internal state of CVoting component.

UI:
- Align callvote button with the rest.
- Increase size of vote reason editbox slightly.
- Increase size of "Force vote" button slightly for other languages.
- Hide voting UI after time elapsed (change to `CVoting::IsVoting`). Prevents UI from continuing into negative time left if server fails to end the vote properly.
- Change vote reason clear button to use X sprite like server browser clear button, instead of manually drawing and handling button.
- Adjust corners, remove one layer of background in the voting menu.

Before:

screenshot_2020-11-17_17-23-20
screenshot_2020-11-17_17-23-14

After:

screenshot_2020-11-19_16-36-02
screenshot_2020-11-19_16-36-14
screenshot_2020-11-19_16-36-09
screenshot_2020-11-19_16-35-57

### CODE REVIEW

**Comment by TsFreddie** [comment]
Have some suggestions looking at the screenshot

* Should we do something about this for good measure?
  * image
* Maybe remove the bottom margin when you are not authed in rcon, so we have less wasted space for non-hosters.
* This margin doesn't seem to do anything, and it is giving the menu a layered hamburger look which is a little bit funny:
  * image

**Comment by TsFreddie** [comment]
I was thinking finding the rects and change the top one to CORNER_T and the bottom one to CORNER_B so they meet in the corner.

**Comment by Robyt3** [comment]
I updated the screenshots above. The spaces should all be consistent now.

**Comment by Robyt3** [comment]
There are still some issue with the alpha of some backgrounds thou, when the menu background alpha is set to something else than 25.

**Comment by Fisico** [comment]
The whole ingame ui is a bit of a mess, it lacks consistency and understandability. In this case there is no logical design way to solve this problem because we have too much layers and even tabs in tabs if you want to call it like that. Normally in tw design the headline container has 25% alpha and the content container on top another 25% and so on. Maximum is three layers so 75% alpha.
A white background is marking the active button.

I made a quick sketch with a white tab header and white headline container, but this is also not ideal.
In a modern UI you would color the whole active tab and at least the headline in a uniform color. Then separate the content with another color. The inactive tabs should be colored darker.


tw_settings

**Comment by Robyt3** [comment]
I think we can open a separate issue about the inconsistent background color alpha and too many background layers in multiple menus (also for example the MOTD). The configurable menu background alpha also behaves inconsistent and only effects some elements. The designers need to specify what the menu is supposed to look like with alpha=0 especially.

**Pull request merged**
